# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: reccenterhq-jquery-rjs 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "reccenterhq-jquery-rjs"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Reccenter HQ", "Akira Matsuda", "Aaron Eisenberger"]
  s.date = "2017-09-28"
  s.description = "Add RJS for jQuery to Rails 3.1+ apps (this repo would probably be the only fork in the world that supports Rails 4)"
  s.email = "jerrod@reccenter.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/action_view/helpers/jquery_helper.rb",
    "lib/action_view/helpers/jquery_ui_helper.rb",
    "lib/action_view/template/handlers/rjs.rb",
    "lib/jquery-rjs.rb",
    "lib/jquery-rjs/javascript_helper.rb",
    "lib/jquery-rjs/on_load_action_controller.rb",
    "lib/jquery-rjs/on_load_action_view.rb",
    "lib/jquery-rjs/renderers.rb",
    "lib/jquery-rjs/rendering.rb",
    "lib/jquery-rjs/selector_assertions.rb"
  ]
  s.homepage = "http://github.com/reccenterhq/jquery-rjs"
  s.rubygems_version = "2.4.6"
  s.summary = "Add RJS for jQuery to Rails 3.1+ apps (this repo would probably be the only fork in the world that supports Rails 4)"
end